##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-utils
    - autoconf-archive
    - clang
    - gcc
    - git
    - itstool
    - libcanberra
    - libgtop
    - make
    - mate-common
    - mate-panel
    - python
    - udisks2
    - which
    - yelp-tools
    # mate-desktop dependencies
    - dconf
    - gobject-introspection
    - iso-codes

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-utils
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - g++
    - git
    - gtk-doc-tools
    - libcanberra-gtk3-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtop2-dev
    - libmate-panel-applet-dev
    - libudisks2-dev
    - libx11-dev
    - libxext-dev
    - libxt-dev
    - make
    - mate-common
    - x11proto-xext-dev
    - xsltproc
    - yelp-tools
    - zlib1g-dev
    # mate-desktop dependencies
    - gobject-introspection
    - iso-codes
    - libdconf-dev
    - libgirepository1.0-dev

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-utils.git
    - autoconf-archive
    - clang
    - clang-analyzer
    - cppcheck-htmlreport
    - desktop-file-utils
    - e2fsprogs-devel
    - gcc
    - gcc-c++
    - git
    - hardlink
    - libX11-devel
    - libXmu-devel
    - libcanberra-devel
    - libgtop2-devel
    - libudisks2-devel
    - make
    - mate-common
    - mate-panel-devel
    - mesa-libGL-devel
    - popt-devel
    - redhat-rpm-config
    - usermode
    - yelp-tools
    # mate-desktop dependencies
    - dconf-devel
    - gobject-introspection-devel
    - iso-codes-devel

  ubuntu:
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - g++
    - git
    - gtk-doc-tools
    - libcanberra-gtk3-dev
    - libdconf-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtop2-dev
    - libmate-panel-applet-dev
    - libudisks2-dev
    - libx11-dev
    - libxext-dev
    - libxt-dev
    - make
    - mate-common
    - x11proto-xext-dev
    - xsltproc
    - yelp-tools
    - zlib1g-dev
    # mate-desktop dependencies
    - gobject-introspection
    - iso-codes
    - libdconf-dev
    - libgirepository1.0-dev

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'
  - MATE_DESKTOP_VERSION=1.27.1

before_scripts:
  - cd ${START_DIR}
  - if [ ! -f mate-desktop-${MATE_DESKTOP_VERSION}.tar.xz ];then
  -     curl -Ls -o mate-desktop-${MATE_DESKTOP_VERSION}.tar.xz https://github.com/mate-desktop/mate-desktop/releases/download/v${MATE_DESKTOP_VERSION}/mate-desktop-${MATE_DESKTOP_VERSION}.tar.xz
  - fi
  - tar xf mate-desktop-${MATE_DESKTOP_VERSION}.tar.xz
  - cd mate-desktop-${MATE_DESKTOP_VERSION}
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./autogen.sh --prefix=/usr
  - fi
  - if [ ${TRAVIS} == "false" ]; then
  -     make clean
  - fi
  - make
  - make install

  - cd ${START_DIR}
  # disable pt language for help in search tool
  - sed -i s/"IGNORE_HELP_LINGUAS ="/"IGNORE_HELP_LINGUAS = pt"/g gsearchtool/help/Makefile.am

build_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     export CFLAGS+=" -Wsign-compare"
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure --enable-compile-warnings=maximum
  - if [ $CPU_COUNT -gt 1 ]; then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make -j $CPU_COUNT
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi

after_scripts:
  - if [ ${DISTRO_NAME} == "fedora" ];then
  -   cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude .
  -   cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=cppcheck-htmlreport
  -   ./gen-index -l 20
  - fi
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-utils-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
